require_relative 'bishop'
require_relative 'king'
require_relative 'pawn'
require_relative 'queen'
require_relative 'rook'
require_relative 'knight'
require_relative 'diagonal_movement_module'
require_relative 'horizontal_movement_module'
require_relative 'slidingpiece'
require_relative 'steppingpiece'
# require_relative 'pieces'
